#! /bin/bash

if [[ $platform == 'linux' ]]; then
  alias ls='ls --color=auto'
elif [[ $platform == 'darwin' ]]; then
  alias ls='ls -G'
fi

alias ..='cd ..'
alias l='ls -lAFh'
alias vim='reattach-to-user-namespace /Applications/MacVim.app/Contents/MacOS/Vim'
alias jdg='ssh -i ~/.ssh/jdg jdg.dyndns.info -R 23053:127.0.0.1:23053 -t tmux a'

command_exists () {
  type "$1" &> /dev/null ;
}

workon() {
  if command_exists tmux ; then
    if [ $# -lt 1 ]
    then
      echo "Usage: workon <session name>"
      echo "Current sessions:"
      tmux list-sessions
      return 1
    fi

    tmux has-session -t $1
    if [ $? != 0 ]
    then
      tmux new-session -s $1 -n vim -d
      tmux split-window -v -t $1
      tmux select-layout -t $1 main-horizontal
      tmux new-window -n console -t $1
      tmux select-window -t $1:1
      tmux attach -t $1
    fi
      tmux attach -t $1
  fi
}
