#! /bin/bash

if [[ $platform == 'linux' ]]; then
   alias ls='ls --color=auto'
elif [[ $platform == 'darwin' ]]; then
   alias ls='ls -G'
fi

alias ..='cd ..'
alias l='ls -lAFh'
alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'
