#! /bin/bash
command_exists () {
  type "$1" &> /dev/null ;
}

if [[ $platform == 'linux' ]]; then
  alias ls='ls --color=auto'
	alias transmissionpermission='sudo chown -R debian-transmission:debian-transmission $1'
elif [[ $platform == 'darwin' ]]; then
  alias ls='ls -G'
  alias vim='reattach-to-user-namespace mvim -v'
  if command_exists autossh ; then
		alias jdg='autossh -M 0 jdg -t tmux a'
	else
		alias jdg='ssh jdg -t tmux a'
	fi
fi

alias ..='cd ..'
# alias l='ls -lAFh'

if ls --color > /dev/null 2>&1; then # GNU `ls`
	colorflag="--color"
else # OS X `ls`
	colorflag="-G"
fi
alias l="ls -l ${colorflag}"
alias ls="command ls ${colorflag}"
export LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'

# Preserves environment variables when running sudo
alias sudo='sudo '

workon() {
  if command_exists tmux ; then
    if [ $# -lt 1 ]
    then
      echo "Usage: workon <session name>"
      echo "Current sessions:"
      tmux list-sessions
      return 1
    fi

    tmux has-session -t $1
    if [ $? != 0 ]
    then
      tmux new-session -s $1 -n vim -d
      tmux split-window -p 25 -v -t $1
      tmux new-window -n console -t $1
      tmux select-window -t $1:1
      tmux attach -t $1
    fi
      tmux attach -t $1
  fi
}
